const faqs = [
  { category: 'General', question: 'What is a hair transplant?', answer: 'A hair transplant is a surgical procedure that moves hair follicles from a donor area (usually the back of your head) to thinning or balding areas. Modern techniques like FUE and DHI ensure minimal scarring and natural-looking results.' },
  { category: 'General', question: 'Am I a good candidate for a hair transplant?', answer: 'Most men and women with pattern hair loss and adequate donor hair are candidates. During your consultation, Dr. [Doctor_Name] will assess your hair loss grade, donor area quality, age, and expectations to determine the best approach.' },
  { category: 'General', question: 'At what age can I get a hair transplant?', answer: 'We generally recommend waiting until age 25+ when hair loss patterns stabilise. However, individual assessment is required — some patients may benefit earlier from medical management before surgery.' },
  { category: 'Procedure', question: 'Is the procedure painful?', answer: 'No. The entire procedure is performed under local anaesthesia, so you feel no pain during the transplant. Most patients watch movies or nap during the session. Mild discomfort afterwards is easily managed with medication.' },
  { category: 'Procedure', question: 'How long does the procedure take?', answer: 'FUE procedures typically take 6–8 hours depending on the number of grafts. DHI may take slightly less. You can have breaks during the procedure for meals and rest.' },
  { category: 'Procedure', question: 'How many grafts will I need?', answer: 'This varies significantly based on your hair loss grade, the area to be covered, and desired density. During consultation, we provide an exact graft estimate. Generally, 1,500–3,500 grafts cover most cases.' },
  { category: 'Recovery', question: 'How long is the recovery?', answer: 'Most patients return to desk work in 3–5 days. Scabs in the transplant area fall off within 10–14 days. We recommend avoiding heavy exercise for 2–3 weeks and direct sun exposure for 4 weeks.' },
  { category: 'Recovery', question: 'When will I see results?', answer: 'Transplanted hair sheds at 2–4 weeks (this is normal — it\'s called "shock loss"). New growth starts at 3–4 months, and you\'ll see significant improvement by 6–8 months. Full results are visible by 12–14 months.' },
  { category: 'Cost', question: 'How much does a hair transplant cost?', answer: 'Cost depends on the technique (FUE vs DHI), number of grafts, and complexity. We provide transparent pricing after your consultation. We also offer EMI and financing options to make treatment accessible.' },
  { category: 'Cost', question: 'Do you accept insurance?', answer: 'Hair transplant procedures are generally considered cosmetic and are not covered by insurance. However, we offer flexible payment plans and EMI options through leading banks.' },
  { category: 'Results', question: 'Will my transplanted hair fall out?', answer: 'Transplanted hair comes from the genetically resistant donor area, so it is permanent. You may lose some non-transplanted hair over time due to ongoing pattern baldness, which can be managed with maintenance treatments.' },
  { category: 'Results', question: 'Will the results look natural?', answer: 'Absolutely. Dr. [Doctor_Name] meticulously designs each hairline considering your facial structure, age, and natural hair growth patterns. Modern techniques place individual follicular units for a completely natural look.' },
  { category: 'Virtual Consult', question: 'How does the virtual consultation work?', answer: 'Submit your photos and medical details through our online form. Dr. [Doctor_Name] will personally review your case and send you a detailed assessment with treatment recommendations within 48 hours.' },
  { category: 'Virtual Consult', question: 'Can I get a transplant without an in-person consultation?', answer: 'A virtual consultation provides a preliminary assessment and treatment plan. However, a final in-person evaluation is required before the actual procedure to confirm graft count and plan the hairline design.' },
];

export default faqs;
